name: greggs_sausage
description: "Challenge Project by Greggs"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.8
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  open_file: ^3.2.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  flutter_zoom_drawer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/resume.pdf


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/greggs_splash.png
  color_dark: "#121212"
  image_dark: assets/images/greggs_splash.png

  android_12:
    image: assets/images/greggs_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/greggs_splash.png
    icon_background_color_dark: "#121212"

  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/greggs_logo.png"
  min_sdk_android: 21